tfidf:
  stop_words:
    - a
    - ao
    - aos
    - aquela
    - aquelas
    - aquele
    - aqueles
    - aquilo
    - as
    - ate
    - atrás
    - bem
    - com
    - como
    - contra
    - da
    - daquele
    - daqueles
    - das
    - de
    - dela
    - delas
    - dele
    - deles
    - depois
    - dessa
    - dessas
    - desse
    - desses
    - desta
    - destas
    - deste
    - destes
    - disso
    - disto
    - do
    - dos
    - e
    - ela
    - elas
    - ele
    - eles
    - em
    - entre
    - era
    - essa
    - essas
    - esse
    - esses
    - esta
    - estas
    - este
    - estes
    - eu
    - foi
    - for
    - fosse
    - haviam
    - isso
    - isto
    - ja
    - lhe
    - lhes
    - mais
    - mas
    - mesmo
    - meu
    - meus
    - minha
    - minhas
    - muito
    - na
    - nao
    - nas
    - nem
    - no
    - nos
    - num
    - numa
    - o
    - os
    - ou
    - para
    - pela
    - pelas
    - pelo
    - pelos
    - por
    - qual
    - quando
    - que
    - seja
    - sem
    - seu
    - seus
    - sua
    - suas
    - também
    - teu
    - teus
    - tua
    - tuas
    - um
    - uma
    - você
    - vocês
  ngram_range: [1, 2]
  max_df: 0.9
  min_df: 2
model:
  algorithm: "LogisticRegression"
  C: 1.0